services:
  backend:
    build: .
    volumes:
      - .:/backend
    ports:
      - '3000:3000'
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mariadb:lts
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
      - MARIADB_USER=${DATABASE_USER}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_DATABASE=${DATABASE_NAME}
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
